// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQpOMcVCOOOCV3MwHsxkZ6nY4jAXeMqJ4',
    appId: '1:220064721385:web:124bf7f0fbb5911af5c378',
    messagingSenderId: '220064721385',
    projectId: 'donor-7d5d6',
    authDomain: 'donor-7d5d6.firebaseapp.com',
    storageBucket: 'donor-7d5d6.appspot.com',
    measurementId: 'G-Z0JF9WCS8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2UGh2Ij9utC2ECgcKkp79IhlBugOHJkg',
    appId: '1:220064721385:android:2b4f31f42a3e4ea3f5c378',
    messagingSenderId: '220064721385',
    projectId: 'donor-7d5d6',
    storageBucket: 'donor-7d5d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7vTkAd_LQpJDS7MrCm2b45yY6UdW3NnU',
    appId: '1:220064721385:ios:fd202624975b2eb3f5c378',
    messagingSenderId: '220064721385',
    projectId: 'donor-7d5d6',
    storageBucket: 'donor-7d5d6.appspot.com',
    iosBundleId: 'com.example.feedonations',
  );
}
